// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrzVxuwFIAEFGM3dwtqAySzwI3JMM06DI',
    appId: '1:166752917601:web:fd95311a3d58500a9bb220',
    messagingSenderId: '166752917601',
    projectId: 'fir-cli-2696b',
    authDomain: 'fir-cli-2696b.firebaseapp.com',
    storageBucket: 'fir-cli-2696b.firebasestorage.app',
    measurementId: 'G-8KTWRKC458',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4_SUjhNwkwsB4lKLTepm6PxTD6Hwi5sw',
    appId: '1:166752917601:android:1ad70f274b5d9fbb9bb220',
    messagingSenderId: '166752917601',
    projectId: 'fir-cli-2696b',
    storageBucket: 'fir-cli-2696b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvICTtCYaT00xzoITjmmYshod55E2Zaqk',
    appId: '1:166752917601:ios:0a462dd2d81f33c49bb220',
    messagingSenderId: '166752917601',
    projectId: 'fir-cli-2696b',
    storageBucket: 'fir-cli-2696b.firebasestorage.app',
    iosBundleId: 'com.example.syedaFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvICTtCYaT00xzoITjmmYshod55E2Zaqk',
    appId: '1:166752917601:ios:0a462dd2d81f33c49bb220',
    messagingSenderId: '166752917601',
    projectId: 'fir-cli-2696b',
    storageBucket: 'fir-cli-2696b.firebasestorage.app',
    iosBundleId: 'com.example.syedaFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrzVxuwFIAEFGM3dwtqAySzwI3JMM06DI',
    appId: '1:166752917601:web:32d493a6740da9a29bb220',
    messagingSenderId: '166752917601',
    projectId: 'fir-cli-2696b',
    authDomain: 'fir-cli-2696b.firebaseapp.com',
    storageBucket: 'fir-cli-2696b.firebasestorage.app',
    measurementId: 'G-CRYR4B7BBD',
  );
}
